FROM tiangolo/node-frontend:10 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
RUN npm run build


FROM nginx:1.15
COPY --from=build-stage /app/frontend/dist/ /www/app/
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY ./configs/nginx/conf.d /etc/nginx/conf.d/
