env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
overrides:
  - files:
      - app/frontend/src/**/*.js
      - app/frontend/src/**/*.jsx
rules:
  react/prop-types: off
  max-len:
    - error
    - 120  # max len
    - 2    # tabs len
