meta:
  schema-version: 0.1.0
  created-on: "2024-07-28T19:17:05Z"
  cli-version: 0.2.0
projects:
  reporterone-reporter:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "5"
    overrides:
      qs:
        6.7.0:
          use: 6.7.0-sp1
        6.5.2:
          use: 6.5.2-sp1
      normalize-url:
        4.5.0:
          use: 4.5.0-sp1
      debug:
        4.1.1:
          use: 4.1.1-sp1
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
      decode-uri-component:
        0.2.0:
          use: 0.2.0-sp1
      scss-tokenizer:
        0.2.3:
          use: 0.2.3-sp1
      node-fetch:
        2.6.0:
          use: 2.6.0-sp1
      acorn:
        5.7.3:
          use: 5.7.3-sp1
      semver:
        6.3.0:
          use: 6.3.0-sp1
        7.0.0:
          use: 7.0.0-sp1
        5.7.1:
          use: 5.7.1-sp1
      nth-check:
        1.0.2:
          use: 1.0.2-sp1
      serialize-javascript:
        1.9.1:
          use: 1.9.1-sp1
      ip:
        1.1.5:
          use: 1.1.5-sp1
      glob-parent:
        3.1.0:
          use: 3.1.0-sp1
      word-wrap:
        1.2.3:
          use: 1.2.3-sp1
      json5:
        2.1.1:
          use: 2.1.1-sp1
        1.0.1:
          use: 1.0.1-sp1
        0.5.1:
          use: 0.5.1-sp1
      loader-utils:
        1.2.3:
          use: 1.2.3-sp2
        0.2.17:
          use: 0.2.17-sp1
      ansi-regex:
        4.1.0:
          use: 4.1.0-sp1
        3.0.0:
          use: 3.0.0-sp1
        5.0.0:
          use: 5.0.0-sp1
      lodash.template:
        4.5.0:
          use: 4.5.0-sp1
      json-schema:
        0.2.3:
          use: 0.2.3-sp1
      got:
        9.6.0:
          use: 9.6.0-sp1
      ejs:
        2.7.4:
          use: 2.7.4-sp2
      webpack-dev-middleware:
        3.7.2:
          use: 3.7.2-sp1
      tmpl:
        1.0.4:
          use: 1.0.4-sp1
      async:
        2.6.3:
          use: 2.6.3-sp1
      minimist:
        0.0.8:
          use: 0.0.8-sp1
        1.2.0:
          use: 1.2.0-sp1
      ini:
        1.3.5:
          use: 1.3.5-sp1
      y18n:
        4.0.0:
          use: 4.0.0-sp1
      elliptic:
        6.5.3:
          use: 6.5.3-sp1
      url-parse:
        1.4.7:
          use: 1.4.7-sp1
      lodash-es:
        4.17.15:
          use: 4.17.15-sp1
      braces:
        2.3.2:
          use: 2.3.2-sp1
