version: '3'

services:
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    ports:
      - 80:9010
    volumes:
      - ./:/app/

  backend:
    build:
      dockerfile: ./backend/Dockerfile
      context: .
    volumes:
      - ./:/app/
