version: '3'

services:
  frontend:
    build:
      dockerfile: ./app/frontend/Dockerfile
      context: .
    ports:
      - 80:80

  backend:
    build:
      dockerfile: ./app/backend/Dockerfile
      context: .
