version: '3'

services:
  frontend:
    build:
      dockerfile: ./app/frontend/Dockerfile
      context: .
    ports:
      - 80:80

  backend:
    build:
      dockerfile: ./app/backend/Dockerfile
      context: .
    environment:
      ONE_REPORT_PORT: 15432

  db:
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: one_report
      POSTGRES_USER: one_report
      POSTGRES_DB: one_report
    ports:
      - 15432:5432