version: '3'

services:
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    ports:
      - 80:80

  backend:
    build:
      dockerfile: ./backend/Dockerfile
      context: .
