"""support repetative statuses and icon path for users

Revision ID: 4cff767f1674
Revises: ee917bbcbe55
Create Date: 2019-12-20 17:46:47.092314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cff767f1674'
down_revision = 'ee917bbcbe55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repetative_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('from_date_id', sa.Integer(), nullable=True),
    sa.Column('to_date_id', sa.Integer(), nullable=True),
    sa.Column('every', sa.Integer(), nullable=True),
    sa.Column('reason_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_date_id'], ['date_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reason_id'], ['reasons.id'], ),
    sa.ForeignKeyConstraint(['to_date_id'], ['date_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_repetative_datas_from_date_id'), 'repetative_datas', ['from_date_id'], unique=False)
    op.create_index(op.f('ix_repetative_datas_reason_id'), 'repetative_datas', ['reason_id'], unique=False)
    op.create_index(op.f('ix_repetative_datas_to_date_id'), 'repetative_datas', ['to_date_id'], unique=False)
    op.create_index(op.f('ix_repetative_datas_user_id'), 'repetative_datas', ['user_id'], unique=False)
    op.add_column('date_datas', sa.Column('reason_id', sa.Integer(), nullable=True))
    op.add_column('date_datas', sa.Column('reported_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_date_datas_reason_id'), 'date_datas', ['reason_id'], unique=False)
    op.create_index(op.f('ix_date_datas_reported_by_id'), 'date_datas', ['reported_by_id'], unique=False)
    op.drop_index('ix_date_datas_reason', table_name='date_datas')
    op.create_unique_constraint(None, 'date_datas', ['id'])
    op.drop_constraint('date_datas_reason_fkey', 'date_datas', type_='foreignkey')
    op.create_foreign_key(None, 'date_datas', 'reasons', ['reason_id'], ['id'])
    op.create_foreign_key(None, 'date_datas', 'users', ['reported_by_id'], ['id'], ondelete='CASCADE')
    op.drop_column('date_datas', 'reason')
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.add_column('reasons', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'reasons', ['id'])
    op.drop_column('reasons', 'reason')
    op.add_column('users', sa.Column('icon_path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'icon_path')
    op.add_column('reasons', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reasons', type_='unique')
    op.drop_column('reasons', 'name')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.add_column('date_datas', sa.Column('reason', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'date_datas', type_='foreignkey')
    op.drop_constraint(None, 'date_datas', type_='foreignkey')
    op.create_foreign_key('date_datas_reason_fkey', 'date_datas', 'reasons', ['reason'], ['id'])
    op.drop_constraint(None, 'date_datas', type_='unique')
    op.create_index('ix_date_datas_reason', 'date_datas', ['reason'], unique=False)
    op.drop_index(op.f('ix_date_datas_reported_by_id'), table_name='date_datas')
    op.drop_index(op.f('ix_date_datas_reason_id'), table_name='date_datas')
    op.drop_column('date_datas', 'reported_by_id')
    op.drop_column('date_datas', 'reason_id')
    op.drop_index(op.f('ix_repetative_datas_user_id'), table_name='repetative_datas')
    op.drop_index(op.f('ix_repetative_datas_to_date_id'), table_name='repetative_datas')
    op.drop_index(op.f('ix_repetative_datas_reason_id'), table_name='repetative_datas')
    op.drop_index(op.f('ix_repetative_datas_from_date_id'), table_name='repetative_datas')
    op.drop_table('repetative_datas')
    # ### end Alembic commands ###
