"""Added price column

Revision ID: 734e5447623f
Revises: 
Create Date: 2019-10-19 05:03:29.522667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734e5447623f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'date_datas', ['id'])
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'reasons', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'reasons', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'date_datas', type_='unique')
    # ### end Alembic commands ###
