"""added email field

Revision ID: 76a466c80ef6
Revises: 914fd311505e
Create Date: 2020-02-08 01:46:11.626695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a466c80ef6'
down_revision = '914fd311505e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'date_datas', ['id'])
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'reasons', ['id'])
    op.create_unique_constraint(None, 'repetative_datas', ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'repetative_datas', type_='unique')
    op.drop_constraint(None, 'reasons', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'date_datas', type_='unique')
    # ### end Alembic commands ###
