"""added_reported_time

Revision ID: bc44eb18ae9a
Revises: 095f9541966a
Create Date: 2019-12-24 13:23:05.956407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc44eb18ae9a'
down_revision = '095f9541966a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date_datas', sa.Column('reported_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'date_datas', ['id'])
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'reasons', ['id'])
    op.add_column('repetative_datas', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('repetative_datas', sa.Column('reported_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'repetative_datas', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'repetative_datas', type_='unique')
    op.drop_column('repetative_datas', 'reported_time')
    op.drop_column('repetative_datas', 'is_active')
    op.drop_constraint(None, 'reasons', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'date_datas', type_='unique')
    op.drop_column('date_datas', 'reported_time')
    # ### end Alembic commands ###
