"""added facebook and google fields

Revision ID: c54dd4ee9d4c
Revises: 76a466c80ef6
Create Date: 2020-02-08 01:54:18.763376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54dd4ee9d4c'
down_revision = '76a466c80ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'facebook_id')
    # ### end Alembic commands ###
