openapi: 3.0.0
info:
  title: one_report v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/v1/dates_status:
    get:
      summary: Get dates status.
      tags:
        - Personal
        - Commander
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../common/models/date.v1.yaml
      description: Get date status.
      parameters:
        - schema:
            type: string
          in: query
          name: start
          required: true
        - schema:
            type: string
          in: query
          name: end
        - schema:
            type: integer
          in: query
          name: user_id
      security:
        - Token: []
      operationId: getDateStatus
    parameters: []
    post:
      summary: ''
      responses:
        '200':
          description: OK
components:
  schemas: {}
  securitySchemes:
    Token:
      name: Token
      type: apiKey
      in: header
